name: Release Workflow

env:
  DOTNET_NOLOGO: true

on:
  workflow_call:
    inputs:
      publish:
          description: Publish to nuget or not
          default: false
          type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: Setup .NET
        uses: actions/setup-dotnet@v4.0.0
        with: { dotnet-version: 8.0.x }

      - name: Setup wasm-tools
        run: dotnet workload install wasm-tools

      - name: Setup tailwindcss
        run: npm install -g tailwindcss

      - name: Setup Nerdbank.GitVersioning
        uses: dotnet/nbgv@v0.4.2
        id: nbgv
        with: { setAllVars: true }

      - name: Restore
        working-directory: src/TabKeeper.UI.Wasm
        run: |
          npm install
          dotnet restore

      - name: Build
        working-directory: src/TabKeeper.UI.Wasm
        run: dotnet build --no-restore

      - name: Publish
        if: ${{ inputs.publish }}
        working-directory: src/TabKeeper.UI.Wasm
        shell: pwsh
        run: |
          .\css.ps1 -publish
          dotnet publish --no-restore --no-build

      - name: Push to Cloudflare Pages
        if: ${{ inputs.publish }}
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: tab-keeper
          directory: artifacts/src/publish/TabKeeper.UI.Wasm/release/wwwroot
          wranglerVersion: '3'