name: Publish Dev Workflow

on:
  workflow_dispatch:
  push:
    branches: [dev]
    paths:
      - "version.json"
      - "src/**/*.cs"
      - "src/**/*.csproj"

jobs:
  publish:
    name: Publish
    uses: panoukos41/TabKeeper/.github/workflows/release.yaml@main
    secrets: inherit