name: Publish

env:
  DOTNET_NOLOGO: true

on:
  workflow_dispatch:
  push:
    branches: [main, dev]
    paths:
      - "version.json"
      - "src/**/*.cs"
      - "src/**/*.csproj"

jobs:
  Build:
    uses: panoukos41/TabKeeper/.github/workflows/_ci.yaml@dev
    with:
      publish: true
    secrets: inherit