name: publish
env: { DOTNET_NOLOGO: true }
on:
  workflow_dispatch:
  push:
    branches:
    - main
    tags:
    - v[0-9]+.[0-9]+.[0-9]+  # Only matches vX.X.X where X is a number
    paths:
    - src/**
    - test/**
jobs:
  determine-environment:
    runs-on: ubuntu-latest
    outputs:
      name: ${{ steps.deployment.outputs.environment }}
    steps:
      - id: deployment
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "environment=dev" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref }}" =~ refs/tags/v[0-9]+.[0-9]+.[0-9]+ ]]; then
            echo "environment=main" >> $GITHUB_OUTPUT
          fi
  pipeline:
    needs: determine-environment
    uses: panoukos41/TabKeeper/.github/workflows/_.yaml@main
    with:
      publish: true
      environment: ${{ needs.determine-environment.outputs.name }}
    secrets:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
