name: Release Workflow

env:
  DOTNET_NOLOGO: true

on:
  workflow_call:
    secrets:
      CLOUDFLARE_API_TOKEN: { required: true }
      CLOUDFLARE_ACCOUNT_ID: { required: true }

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4.0.0
        with: { dotnet-version: 8.0.x, cache: true }

      - name: Setup wasm-tools workload
        run: dotnet workload install wasm-tools

      - name: Setup tailwindcss
        run: npm install -g tailwindcss

      - name: Nerdbank.GitVersioning
        uses: dotnet/nbgv@v0.4.2
        id: nbgv
        with: { setAllVars: true }

      - name: Restore
        run: |
          npm install
          dotnet restore

      - name: Publish
        working-directory: src/TabKeeper.UI.Wasm
        shell: pwsh
        run: |
          .\css.ps1 -publish
          dotnet publish --no-restore

      - name: Upload to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: tab-keeper
          directory: artifacts/src/publish/TabKeeper.UI.Wasm/release/wwwroot
          wranglerVersion: '3'